name: Daily autoCard

on:
  workflow_dispatch:
  schedule:
    - cron: "5 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run application
        env:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
        run: python -u main.py
